# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'akumina-ios-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for akumina-ios-sample
  pod 'AkuminaAuthiOSLib'

  target 'akumina-ios-sampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'akumina-ios-sampleUITests' do
    # Pods for testing
  end

end
